Lemonexe/group pending transanctions by date v2
Lemonexe/trezor-suite pull request #1
Opened 2024-06-06 15:18 UTC by Lemonexe

## Description

## Related Issue

Resolve 

## Screenshots:

2024-06-06 15:37 UTC, Lemonexe commented on packages/suite/src/views/wallet/transactions/Transactions.tsx
> +    // TODO REVERT THIS COMMIT
⚠️ testing data, revert me before merging

2024-06-06 15:58 UTC, Lemonexe commented on suite-common/wallet-utils/src/transactionUtils.ts
> +): GroupedTransactionsByDate => {
Explicit return type will make it quicker to catch mistakes during future refactoring (although yes, the fn has tests)

2024-06-06 16:03 UTC, Lemonexe commented on packages/suite/src/views/wallet/transactions/TransactionList/TransactionsGroup/GroupHeaders.tsx
> -            {dateKey === 'pending' ? (
IMHO this component had too many concerns. Displaying date vs. pending transactions header are very different concerns, and looking differently too, so it should be split into two components rather than if else.

Now this file exports multiple components. If it is unacceptable, I can split it into two files for each headers, and one for common components.

2024-06-06 16:07 UTC, Lemonexe commented on packages/suite/src/views/wallet/transactions/TransactionList/TransactionList.tsx
> +    // TODO use one fn call to split pending & confirmed instead of two filters (use lib fn such as ramda partition)
Neither `ramda` or `fp-ts` is used – those are toolbox libs I am familiar with.
Is there another lib that I don't know, which has the desired function?
If not, it can be done locally with `Array.reduce` 🙂

2024-06-07 10:16 UTC, komret requested changes
Well done, I like your approach and the improvements you have made. Not ready to be merged though, due to tests and mobile app.

2024-06-16 15:48 UTC, Lemonexe commented on packages/suite/src/views/wallet/transactions/TransactionList/TransactionsGroup/CommonComponents.tsx
> +import styled from 'styled-components';
I wondered about the name of this file, and found out "CommonComponents" is already used within [the suite package](https://github.com/Lemonexe/trezor-suite/blob/e81a203a585f8ae706d4070447f83157ec99c005/packages/suite/src/components/wallet/TransactionItem/CommonComponents.tsx).

2024-06-16 17:30 UTC, Lemonexe commented on suite-common/wallet-utils/src/transactionUtils.ts
> +    groupPendingAlsoByDate = false,
Done. As I don't have dev environment for `suite-native`, it'd be best if someone verified that the code behaves as it did originally.

2024-06-16 17:34 UTC, Lemonexe commented on suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
> +        const confirmedTxs = transactions.filter(tx => !isPending(tx));
I wanted to use `arrayPartition`, but trezor utils are not installed here in suite-native/transactions.
I tried installing it in https://github.com/Lemonexe/trezor-suite/pull/1/commits/8b19a2caaf70da1530f3127dd85c6b1d5a75b0a1, but that [threw me an error](https://github.com/Lemonexe/trezor-suite/actions/runs/9537738515/job/26286151914?pr=1), apparently it's forbidden to modify lock file..?

2024-06-16 17:47 UTC, Lemonexe commented on suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts
> -            getWalletTransaction({ blockHeight: 0 }),
Note: test case for `{ blockHeight: 0 }` or `{ blockHeight: undefined }` is not valuable anymore

The new behavior is, that falsey `blockHeight` but truthy `blockTime` is also sorted by date, not as pending.
These ones get the default `blockTime` [from the mock](https://github.com/Lemonexe/trezor-suite/blob/e9a042518338e1b23fbf1542d4f08ea64dd930cd/suite-common/test-utils/src/mocks.ts#L213), and get sorted by it. Relying on it would just make the test poorly readable – it's better to specify `blockTime` explicitly.

2024-06-16 17:53 UTC, Lemonexe commented
Note: conventional commit messages are still failing. Looking at currently active PRs I see that it is customary to make just one or two commits per PR, and rebase&merge them instead of squash&merge the feature branch.

For the time being I wanted to keep the "story" told by my commit history, but I can squash my branch into one commit with conventional name, that's no problem..

2024-08-07 07:14 UTC, Lemonexe commented
Closing, because the PR was duplicated in main repo https://github.com/trezor/trezor-suite/pull/12975

2024-08-07 07:14 UTC, closed without merging